# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/system-essentials

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Import User Management
  ansible.builtin.import_tasks: users.yml

- name: Import Auto Updates
  ansible.builtin.import_tasks: auto-updates.yml

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - sudo
      - net-tools
    state: present
