# SPDX-License-Identifier: MIT-0
---
# defaults file for roles/docker-runtime

# The user that will manage Docker containers (usually the one connecting via SSH)
docker_admin_user: "{{ ansible_user }}"
