services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /root/stacks:/root/stacks
    environment:
      - DOCKGE_STACKS_DIR=/root/stacks
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.rule=Host(`dockge.cavydev.com`)
      - traefik.http.routers.dockge.entrypoints=websecure
      - traefik.http.routers.dockge.tls.certresolver=myresolver
      - traefik.http.routers.dockge.middlewares=authentik-auth@docker
      - traefik.http.services.dockge.loadbalancer.server.port=5001
networks:
  proxy-network:
    external: true
