galaxy_info:
  author: Adam Benyekkou
  description: Homelab vault-secrets role
  company: CavyDev
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
