#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/system-essentials

# List of essential packages to install on all servers
essential_packages:
  - git
  - curl
  - jq
  - vim
  - htop
  - ufw
  - apt-transport-https
  - ca-certificates
