---
- name: Routine Maintenance
  hosts: all
  become: yes
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        autoclean: true
        autoremove: true

    # - name: Clean Docker system
    #   community.docker.docker_prune:
    #     containers: true
    #     images: true
    #     networks: true
    #     volumes: no
    #     builder_cache: true


    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
```
