services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    networks:
      - proxy-network
      - gitea-internal
    volumes:
      - /root/stacks/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
      - GITEA__server__DOMAIN=${GITEA__server__DOMAIN}
      - GITEA__server__SSH_DOMAIN=${GITEA__server__SSH_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA__server__ROOT_URL}
      - GITEA__server__PROTOCOL=${GITEA__server__PROTOCOL}
      - GITEA__server__SSH_PORT=${GITEA__server__SSH_PORT}
      - GITEA__server__LFS_START_SERVER=${GITEA__server__LFS_START_SERVER}
      - GITEA__migrations__ALLOWED_DOMAINS=${GITEA__migrations__ALLOWED_DOMAINS}
      - GITEA__migrations__ALLOW_LOCALNETWORKS=${GITEA__migrations__ALLOW_LOCALNETWORKS}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA__service__DISABLE_REGISTRATION}
    ports:
      - 2222:22
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${GITEA__server__DOMAIN}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=myresolver
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.docker.network=proxy-network

  gitea-db:
    image: postgres:15
    container_name: gitea-db
    restart: always
    networks:
      - gitea-internal
    environment:
      - POSTGRES_USER=${GITEA__database__USER}
      - POSTGRES_PASSWORD=${GITEA__database__PASSWD}
      - POSTGRES_DB=${GITEA__database__NAME}
    volumes:
      - /root/stacks/gitea/db-data:/var/lib/postgresql/data

networks:
  gitea-internal:
    external: false
  proxy-network:
    external: true