services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--global.checknewversion=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ton-email@cavydev.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.cavydev.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-dash.service=api@internal"
      - "traefik.http.routers.traefik-dash.entrypoints=websecure"
      - "traefik.http.routers.traefik-dash.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dash.middlewares=authentik-auth@docker"
      - "traefik.http.routers.traefik-auth.rule=Host(`traefik.cavydev.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.traefik-auth.entrypoints=websecure"
      - "traefik.http.routers.traefik-auth.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-auth.middlewares=authentik-auth@docker"
      - "traefik.http.routers.traefik-auth.service=authentik-service"
      - "traefik.http.middlewares.authentik-auth.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik-auth.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
      - "traefik.http.services.authentik-service.loadbalancer.server.port=9000"

networks:
  proxy-network:
    external: true
