services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - CRON_MIN=1,31
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.cavydev.com`)
      - traefik.http.routers.freshrss.entrypoints=websecure
      - traefik.http.routers.freshrss.tls.certresolver=myresolver
      - traefik.http.routers.freshrss.middlewares=authentik-auth@docker
      - traefik.http.services.freshrss.loadbalancer.server.port=80
networks:
  proxy-network:
    external: true
